Content:
    - framework/doc/content
    - modules/tensor_mechanics/doc/content
    - modules/peridynamics/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE Peridynamics Module
        repo: https://github.com/idaholab/moose
        home: /modules/peridynamics/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/peridynamics
        remove:
            framework: !include framework/doc/remove.yml
        unregister:
            framework: !include framework/doc/unregister.yml
        includes:
            - framework/include
            - modules/peridynamics/include
            - modules/tensor_mechanics/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
