Content:
    ccb:
        root_dir: ${MOOSE_DIR}/modules/doc/training/content
        content:
            - sqa/training/lead/**

Executioner: !include ${MOOSE_DIR}/modules/doc/training/sqa_lead_config.yml Executioner
Renderer: !include ${MOOSE_DIR}/modules/doc/training/sqa_lead_config.yml Renderer
Extensions: !include ${MOOSE_DIR}/modules/doc/training/sqa_lead_config.yml Extensions
