Content:
    - framework/doc/content
    - modules/rdg/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE rDG Module
        repo: https://github.com/idaholab/moose
        home: /modules/rdg/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/rdg
        remove:
            framework: !include framework/doc/remove.yml
        unregister:
            framework: !include framework/doc/unregister.yml
        includes:
            - framework/include
            - modules/rdg/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.sqa:
        active: True
        reports: !include modules/rdg/doc/sqa_reports.yml
        categories:
            framework: !include framework/doc/sqa_framework.yml
            rdg: !include modules/rdg/doc/sqa_rdg.yml
