# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   template/ (must contain any python major.minor version this
#              package supports. Usually the latest version.)
#   moose/
#   moose-dev/
{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "2023.05.01" %}

package:
  name: moose-wasp
  version: {{ version }}

source:
  - path: ../../framework/contrib/wasp
  - path: ../../scripts/configure_wasp.sh

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
  run_exports:
    - {{ pin_subpackage('moose-wasp', max_pin='x.x')}}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config

about:
  home: https://code.ornl.gov/neams-workbench/wasp
  license: OPEN SOURCE LICENSE (Permissive)
  license_file: LICENSE
  summary: >
    The Workbench Analysis Sequence Processor (WASP) was developed to streamline lexing, parsing,
    access, validation, and analysis of ascii text files.
extra:
  recipe-maintainers:
    - milljm
    - loganharbour
