Content:
    ccb:
        root_dir: ${MOOSE_DIR}/modules/doc/training/content/sqa/training/lead
        content:
            - index.md
            - sqa_moosedocs.md
            - sqa_review.md
            - sqa_civet.md
            - sqa_release.md

    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - contrib/**
            - css/**
            - js/**

    large_media:
        root_dir: ${MOOSE_DIR}/large_media
        content:
            - tutorials/INL_Hex_Light_Presentation_Background.jpg

Executioner:
    type: MooseDocs.base.Serial

Renderer:
    type: MooseDocs.base.RevealRenderer
    theme: simple

Extensions:
    disable_defaults: True
    MooseDocs.extensions.comment: default
    MooseDocs.extensions.command: default
    MooseDocs.extensions.core: default
    MooseDocs.extensions.config: default
    MooseDocs.extensions.media: default
    MooseDocs.extensions.floats: default
    MooseDocs.extensions.include: default
    MooseDocs.extensions.bibtex: default
    MooseDocs.extensions.katex: default
    MooseDocs.extensions.style: default
    MooseDocs.extensions.autolink: default
    MooseDocs.extensions.materialicon: default
    MooseDocs.extensions.heading: default
    MooseDocs.extensions.table: default
    MooseDocs.extensions.content: default
    MooseDocs.extensions.modal: default
    MooseDocs.extensions.alert: default
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.listing:
        modal-link: False
    MooseDocs.extensions.reveal:
        translate: ${MOOSE_DIR}/modules/doc/training/content/sqa/training/lead/index.md
        background_image: INL_Hex_Light_Presentation_Background.jpg
    MooseDocs.extensions.bibtex:
        duplicates: !include modules/doc/duplicate_bibs.yml
