moose_mpich:
  - moose-mpich 4.0.2 build_8

moose_petsc:
  - moose-petsc 3.16.6

moose_libmesh_vtk:
  - moose-libmesh-vtk 9.2.6

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.12.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
