# Do not alter <VERSION>, <SKIP_DOCS>. These are template tokens altered
# on the fly by civet recipes. The only modifiable item in moose/ is the
# conda_build_config.yaml file (moose_libmesh)
{% set VERSION = "<VERSION>" %}
{% set SKIP_DOCS = "<SKIP_DOCS>" %}
{% set build = 0 %}
{% set strbuild = "build_" + build|string %}

package:
  name: moose
  version: {{ VERSION }}

source:
  - path: ../../../moose

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true # [win]
  pin_depends: strict
  script_env:
    - MOOSE_JOBS
    - SKIP_DOCS={{ SKIP_DOCS }}

requirements:
  build:
    - {{ moose_libmesh }}
    - {{ moose_python }}
    - moose-tools

  run:
    - {{ moose_libmesh }}
    - {{ moose_python }}
    - {{ moose_wasp }}
    - moose-tools

test:
  script: run_test.sh
  commands:
    - $PREFIX/moose/bin/combined-opt -h
    - $PREFIX/bin/moose-opt -h
    - $PREFIX/bin/moose -h

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: >
   The Multiphysics Object-Oriented Simulation Environment (MOOSE) is a finite-element,
   multiphysics framework primarily developed by Idaho National Laboratory. This superficial module
   (moose) if a future placeholder for binary releases of MOOSE.

extra:
  recipe-maintainers:
    - milljm
