Content:
    framework:
        root_dir: framework/doc/content
        content:
            - contrib/**
            - css/**
            - js/**
    combined:
        root_dir: modules/combined/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    disable_defaults: True
    MooseDocs.extensions.core: default
