Content:
    - framework/doc/content
    - modules/reactor/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: reactor
        repo: https://github.com/idaholab/moose
        home: /modules/reactor
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/reactor
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/reactor/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: True
        reports: !include modules/reactor/doc/sqa_reports.yml
        categories:
            framework: !include framework/doc/sqa_framework.yml
            reactor: !include modules/reactor/doc/sqa_reactor.yml
