# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   template/ (must contain any python major.minor version this
#              package supports. Usually the latest version.)
#   moose-dev/
#
# If adding a new Python version, you will need to update
# version in mpich/meta.yaml:
#
# run_constrains:
#     - python <{{version}}
#
# as well as follow the directions pertaining to modifying that file.
{% set build = 0 %}
{% set version = "2023.05.12" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: ../tools

build:
  number: {{ build }}

requirements:
  build:
    - {{ moose_python }}
    - setuptools
  run:
    - moose-test-tools
    - beautifulsoup4
    - livereload
    - pybtex
    - mock
    - pylatexenc
    - python
    - clang-tools 12.0.1

test:
  commands:
    - git clang-format -h
  imports:
    - bs4
    - livereload
    - pybtex
    - mock
    - pylatexenc

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: >
    This superficial module (moose-tools) acts as a top-level module designed to provide all
    dependencies required in order to run the TestHarness, clang-format, and create MOOSE
    Documentation.

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
    - loganharbour
