Content:
    intro_slides:
        root_dir: modules/navier_stokes/doc/intro_slides

Executioner:
    type: MooseDocs.base.Serial

Renderer:
    type: MooseDocs.base.RevealRenderer
    theme: simple

Extensions:
    disable_defaults: True
    MooseDocs.extensions.comment: default
    MooseDocs.extensions.command: default
    MooseDocs.extensions.core: default
    MooseDocs.extensions.config: default
    MooseDocs.extensions.media: default
    MooseDocs.extensions.floats: default
    MooseDocs.extensions.include: default
    MooseDocs.extensions.bibtex:
        duplicates: !include modules/doc/duplicate_bibs.yml # necessary when building with main site
    MooseDocs.extensions.katex:
        macros:
            \vec: "\\bar" # TODO: \vec doesn't render
            \pf: "\\frac{\\partial #1}{\\partial #2}"
    MooseDocs.extensions.style: default
    MooseDocs.extensions.autolink: default
    MooseDocs.extensions.materialicon: default
    MooseDocs.extensions.heading: default
    MooseDocs.extensions.shortcut: default
    MooseDocs.extensions.table: default
    MooseDocs.extensions.layout: default
    MooseDocs.extensions.content: default
    MooseDocs.extensions.modal: default
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.listing:
        modal-link: False
    MooseDocs.extensions.reveal:
        translate: slides/index.md
        background_image: INL_Hex_Light_Presentation_Background_Thin.png
    MooseDocs.extensions.datetime: default
