{% set build = 0 %}
{% set version = "2022.12.05" %}

package:
  name: moose-peacock
  version: {{ version }}

source:
  path: ../peacock

build:
  number: {{ build }}
  pin_depends: strict

requirements:
  build:
    - {{ moose_python }}
    - setuptools
  run:
    - {{ moose_pyqt }}
    - {{ moose_qt }}
    - {{ moose_matplotlib }}
    - {{ moose_vtk }}
    - pandas
    - python
    - setuptools

test:
  imports:
    - PyQt5
    - matplotlib
    - pandas
    - vtk

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: >
    This superficial module (moose-peacock) acts as a top-level module designed to provide all
    dependencies required in order to run Peacock.

extra:
  recipe-maintainers:
    - milljm
