moose_python:
  - python 3.10
  - python 3.9
  - python 3.8

# Pesky packages that break internal CI
# Note: Modifying/Updating this will require changes to conda/mpich!
setuptools:
  - <60.0
pin_run_as_build:
  setuptools: x.x

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX10.12.sdk                                    # [not arm64 and osx]
  - /opt/MacOSX11.3.sdk                                     # [arm64]

macos_min_version:                                          # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.12                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64]
