{% set build = "<BUILD>" %}
{% set version = "<VERSION>" %}
{% set strbuild = "build_" + build|string %}

package:
  name: <PREFIX_PACKAGE_WITH><FORMATTED_APPLICATION>
  version: {{ version }}

source:
  path: .

build:
  number: {{ build }}  # [linux,osx]
  string: {{ strbuild }}
  skip: true # [win]

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'The Multiphysics Object-Oriented Simulation Environment (MOOSE) is a finite-element, multiphysics framework primarily developed by Idaho National Laboratory. This superficial module (moose) if a future placeholder for binary releases of MOOSE.'

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
    - loganharbour
