Content:
    tutorial03_verification:
        root_dir: ${MOOSE_DIR}/tutorials/tutorial03_verification/doc/content
    darcy_thermo_mech:
        root_dir: ${MOOSE_DIR}/tutorials/darcy_thermo_mech/doc/content
        content:
            - workshop/intro/**
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - contrib/**
            - css/**
            - js/**
    modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - getting_started/examples_and_tutorials/tutorial03_verification/references.bib
    large_media:
        root_dir: ${MOOSE_DIR}/large_media
        content:
            - tutorials/tutorial03_verification/*
            - tutorials/darcy_thermo_mech/*
            - tutorials/INL_Hex_Light_Presentation_Background.jpg
            - python/mms/*

Executioner:
    type: MooseDocs.base.Serial

Renderer:
    type: MooseDocs.base.RevealRenderer
    theme: simple

Extensions:
    disable_defaults: True
    MooseDocs.extensions.comment: default
    MooseDocs.extensions.command: default
    MooseDocs.extensions.core: default
    MooseDocs.extensions.config: default
    MooseDocs.extensions.media: default
    MooseDocs.extensions.floats: default
    MooseDocs.extensions.include: default
    MooseDocs.extensions.bibtex:
        duplicates: !include modules/doc/duplicate_bibs.yml # necessary when building with main site
    MooseDocs.extensions.katex: default
    MooseDocs.extensions.style: default
    MooseDocs.extensions.autolink: default
    MooseDocs.extensions.materialicon: default
    MooseDocs.extensions.heading: default
    MooseDocs.extensions.table: default
    MooseDocs.extensions.content: default
    MooseDocs.extensions.modal: default
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.listing:
        modal-link: False
    MooseDocs.extensions.reveal:
        translate: getting_started/examples_and_tutorials/tutorial03_verification/presentation/index.md
        background_image: INL_Hex_Light_Presentation_Background.jpg
